// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: TopLevelContent
			nil,       // empty
			shift(5),  // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // empty
			nil,          // id
			nil,          // [
			nil,          // ]
			nil,          // ;
			nil,          // edgearrow
			nil,          // edge_attr_open
			nil,          // edge_attr_close
			nil,          // =
			nil,          // ,
			nil,          // numeric_literal
			nil,          // quoted_string
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: TopLevelContent
			nil,       // empty
			shift(5),  // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: TopLevelDeclList
			nil,       // empty
			reduce(3), // id, reduce: TopLevelDeclList
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(21), // ␚, reduce: TopLevelStmt
			nil,        // empty
			reduce(21), // id, reduce: TopLevelStmt
			nil,        // [
			nil,        // ]
			shift(8),   // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // ␚, reduce: NodeDecl
			nil,       // empty
			reduce(9), // id, reduce: NodeDecl
			shift(9),  // [
			nil,       // ]
			reduce(9), // ;, reduce: NodeDecl
			shift(11), // edgearrow
			shift(12), // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(19), // ␚, reduce: TopLevelStmt
			nil,        // empty
			reduce(19), // id, reduce: TopLevelStmt
			nil,        // [
			nil,        // ]
			shift(13),  // ;
			shift(11),  // edgearrow
			shift(12),  // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: TopLevelDeclList
			nil,       // empty
			reduce(4), // id, reduce: TopLevelDeclList
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(22), // ␚, reduce: TopLevelStmt
			nil,        // empty
			reduce(22), // id, reduce: TopLevelStmt
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(15), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // ␚, reduce: EdgeDecl
			nil,        // empty
			reduce(17), // id, reduce: EdgeDecl
			nil,        // [
			nil,        // ]
			reduce(17), // ;, reduce: EdgeDecl
			reduce(17), // edgearrow, reduce: EdgeDecl
			reduce(17), // edge_attr_open, reduce: EdgeDecl
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(18), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(19), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(21), // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(20), // ␚, reduce: TopLevelStmt
			nil,        // empty
			reduce(20), // id, reduce: TopLevelStmt
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(18), // ␚, reduce: EdgeDecl
			nil,        // empty
			reduce(18), // id, reduce: EdgeDecl
			nil,        // [
			nil,        // ]
			reduce(18), // ;, reduce: EdgeDecl
			reduce(18), // edgearrow, reduce: EdgeDecl
			reduce(18), // edge_attr_open, reduce: EdgeDecl
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(23), // id
			nil,       // [
			shift(25), // ]
			shift(26), // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			shift(27), // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(23), // id
			nil,       // [
			shift(28), // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(23), // id, reduce: AttrItems
			nil,        // [
			reduce(23), // ], reduce: AttrItems
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(10), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(10), // ;, reduce: EdgeRHS
			reduce(10), // edgearrow, reduce: EdgeRHS
			reduce(10), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // id
			nil,       // [
			nil,       // ]
			shift(32), // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(33), // edge_attr_close
			shift(34), // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(35), // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(37), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(23), // id, reduce: AttrItems
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(23), // edge_attr_close, reduce: AttrItems
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			shift(27), // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(23), // id
			nil,       // [
			shift(38), // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // ␚, reduce: NodeDecl
			nil,       // empty
			reduce(8), // id, reduce: NodeDecl
			nil,       // [
			nil,       // ]
			reduce(8), // ;, reduce: NodeDecl
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(23), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(40), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			shift(42), // numeric_literal
			shift(43), // quoted_string
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: NodeDecl
			nil,       // empty
			reduce(5), // id, reduce: NodeDecl
			nil,       // [
			nil,       // ]
			reduce(5), // ;, reduce: NodeDecl
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(24), // id, reduce: AttrItems
			nil,        // [
			reduce(24), // ], reduce: AttrItems
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			shift(34), // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(44), // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(46), // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(47), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(48), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			shift(50), // numeric_literal
			shift(51), // quoted_string
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(52), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(24), // id, reduce: AttrItems
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(24), // edge_attr_close, reduce: AttrItems
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(11), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(11), // ;, reduce: EdgeRHS
			reduce(11), // edgearrow, reduce: EdgeRHS
			reduce(11), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: NodeDecl
			nil,       // empty
			reduce(6), // id, reduce: NodeDecl
			nil,       // [
			nil,       // ]
			reduce(6), // ;, reduce: NodeDecl
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(23), // id
			nil,       // [
			shift(53), // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(27), // id, reduce: AttrVal
			nil,        // [
			reduce(27), // ], reduce: AttrVal
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			reduce(27), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(25), // id, reduce: Attr
			nil,        // [
			reduce(25), // ], reduce: Attr
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			shift(54),  // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(28), // id, reduce: AttrVal
			nil,        // [
			reduce(28), // ], reduce: AttrVal
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			reduce(28), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(29), // id, reduce: AttrVal
			nil,        // [
			reduce(29), // ], reduce: AttrVal
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			reduce(29), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(55), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(30), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			shift(56), // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(57), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(13), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(13), // ;, reduce: EdgeRHS
			reduce(13), // edgearrow, reduce: EdgeRHS
			reduce(13), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(27), // id, reduce: AttrVal
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(27), // edge_attr_close, reduce: AttrVal
			nil,        // =
			reduce(27), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(25), // id, reduce: Attr
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(25), // edge_attr_close, reduce: Attr
			nil,        // =
			shift(58),  // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(28), // id, reduce: AttrVal
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(28), // edge_attr_close, reduce: AttrVal
			nil,        // =
			reduce(28), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(29), // id, reduce: AttrVal
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(29), // edge_attr_close, reduce: AttrVal
			nil,        // =
			reduce(29), // ,, reduce: AttrVal
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(12), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(12), // ;, reduce: EdgeRHS
			reduce(12), // edgearrow, reduce: EdgeRHS
			reduce(12), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // ␚, reduce: NodeDecl
			nil,       // empty
			reduce(7), // id, reduce: NodeDecl
			nil,       // [
			nil,       // ]
			reduce(7), // ;, reduce: NodeDecl
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(26), // id, reduce: Attr
			nil,        // [
			reduce(26), // ], reduce: Attr
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(15), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(15), // ;, reduce: EdgeRHS
			reduce(15), // edgearrow, reduce: EdgeRHS
			reduce(15), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(59), // id
			nil,       // [
			nil,       // ]
			nil,       // ;
			nil,       // edgearrow
			nil,       // edge_attr_open
			nil,       // edge_attr_close
			nil,       // =
			nil,       // ,
			nil,       // numeric_literal
			nil,       // quoted_string
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(14), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(14), // ;, reduce: EdgeRHS
			reduce(14), // edgearrow, reduce: EdgeRHS
			reduce(14), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(26), // id, reduce: Attr
			nil,        // [
			nil,        // ]
			nil,        // ;
			nil,        // edgearrow
			nil,        // edge_attr_open
			reduce(26), // edge_attr_close, reduce: Attr
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // ␚, reduce: EdgeRHS
			nil,        // empty
			reduce(16), // id, reduce: EdgeRHS
			nil,        // [
			nil,        // ]
			reduce(16), // ;, reduce: EdgeRHS
			reduce(16), // edgearrow, reduce: EdgeRHS
			reduce(16), // edge_attr_open, reduce: EdgeRHS
			nil,        // edge_attr_close
			nil,        // =
			nil,        // ,
			nil,        // numeric_literal
			nil,        // quoted_string
		},
	},
}
