// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // TopLevelContent
		2,  // TopLevelDeclList
		4,  // NodeDecl
		-1, // EdgeRHS
		6,  // EdgeDecl
		3,  // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S1
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S2
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		4,  // NodeDecl
		-1, // EdgeRHS
		6,  // EdgeDecl
		7,  // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S3
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S4
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S5
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		10, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S6
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		14, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S7
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S8
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S9
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		16, // AttrItems
		17, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S10
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S11
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S12
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		20, // AttrItems
		22, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S13
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S14
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S15
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		24, // AttrItems
		17, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S16
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		29, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S17
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S18
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S19
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		31, // AttrItems
		22, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S20
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		36, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S21
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S22
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S23
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S24
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		29, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S25
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S26
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		39, // AttrItems
		17, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S27
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		41, // AttrVal
	},
	gotoRow{ // S28
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S29
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S30
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S31
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		36, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S32
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		43, // AttrItems
		22, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S33
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S34
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		47, // AttrVal
	},
	gotoRow{ // S35
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S36
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S37
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S38
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S39
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		29, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S40
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S41
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S42
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S43
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		36, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S44
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S45
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S46
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S47
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S48
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S49
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S50
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S51
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S52
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S53
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S54
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
	gotoRow{ // S55
		-1, // S'
		-1, // TopLevelContent
		-1, // TopLevelDeclList
		-1, // NodeDecl
		-1, // EdgeRHS
		-1, // EdgeDecl
		-1, // TopLevelStmt
		-1, // AttrItems
		-1, // Attr
		-1, // AttrVal
	},
}
