on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_ver:
          - {id: 'stable', gosetupargs: {go-version: 'stable'}}
          - {id: 'oldstable' ,gosetupargs: {go-version: 'oldstable'}}
          - {id: 'from-go-mod', gosetupargs: {go-version-file: 'go.mod'}}
    name: CI w/ go version '${{ matrix.go_ver.id }}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: ${{ matrix.go_ver.gosetupargs }}

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./... 

      - name: Test
        run: go test -v ./...

  # Separate job; partly for parallelism, partly to avoid any possible
  # shenanigans with triplicate annotations etc.
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
